backend:
  name: github
  repo: oherst/gatsby-test

media_folder: static/assets
public_folder: assets

collections:
  - label: Blog
    name: blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
  - label: "Pages"
    name: "pages"
    files:
      - label: "About Page"
        name: "about"
        file: "src/pages/about/index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Team
            name: team
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Position, name: position, widget: string}
              - {label: Photo, name: photo, widget: image}
